services:
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    restart: unless-stopped
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    # Uncomment below to use byparr outside of internal network
    # ports:
    #   - "8191:8191"
